Fixed the error "!!! error TS7022: 'ba' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer." that was introduced by in case VariableDeclaration of mrNarrowTypesInner.  That resulted in "getTypesOfSymbol" being called from "applyCritToArrRefTypesTableReturn".
Next: Add "declaredTypes" table to state.  In the "case Identifier", it will be set with "getTypeOfSymbol" in mrNarrowTypesInner.
In the "case VariableDeclaration" it will be set with the rhs of the declaration.
It can be read from "applyCritToArrRefTypesTableReturn" or anywhere else it is required.

 On branch condalias-49075-work-2
 Changes to be committed:
	modified:   src/compiler/checker.ts
	modified:   src/compiler/flowGroupInfer2.ts